# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc7d5109e0c9fbad3bdafddba5f833d1911ca2dc51c1cb9b2486da39813f02e7eecaf353914ff23ad073af61b6b88d9dc1510df4b79347980601bcef1b30cdd

test:
  secret_key_base: f96ab37e84e98bd9a810242a0ffa0034862db3edfeb0096fe21a2935a9e4a5a06f453b922973606dde9378ae566bcfda989ed14ef9ccd339be1002bb5190b5d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
